apiVersion: v1
kind: ConfigMap
metadata:
  name: bh-audit-config
  namespace: default
data:
  NODE_ENV: "production"
  DB_HOST: "bh-audit-db-service"
  DB_PORT: "5432"
  DB_NAME: "bh_audit"
  PORT: "3001"