apiVersion: apps/v1
kind: Deployment
metadata:
  name: bh-core-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bh-core-db
  template:
    metadata:
      labels:
        app: bh-core-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "bh_core"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: bh-core-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bh-core-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: bh-core-db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: bh-core-db-data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: bh-core-db-service
  namespace: default
spec:
  selector:
    app: bh-core-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP